// this bit is just plain Jenkins Groovy
def secretsDirectory = new File("/secret/jenkins-secrets").exists() ? new File("/secret/jenkins-secrets") : new File("/var/jenkins_secrets");
def randomUUID = "${UUID.randomUUID().toString()}"
def randomLabel = "jenkins-worker-${randomUUID}"
def dockerRegistryAddress = new File(secretsDirectory, "dockerRegistryAddress").text.trim();
def jenkinsAgentImageTag = new File(secretsDirectory, "cloudOpsForKubernetesDefaultBranch").text.trim().replace('/','-');

def sharedSteps() {
  // load EP Groovy Library
  eplib = load "cloudops-for-kubernetes/lib/eplib.groovy"
  buildlib = load "cloudops-for-kubernetes/lib/buildlib.groovy"

  eplib.loginToCloud()
  eplib.loginToDockerRegistry()
}

// this is a workaround until this bug is fixed: https://issues.jenkins-ci.org/browse/JENKINS-56943
def podYamlFromFile = new File("${env.JENKINS_HOME}/workspace/build-core-images@script/cloudops-for-kubernetes/jenkins/agents/kubernetes/docker-4gb-2core-1container.yaml").text.trim();
String podYaml = podYamlFromFile.replace('${dockerRegistryAddress}', "${dockerRegistryAddress}").replace('${jenkinsAgentImageTag}', "${jenkinsAgentImageTag}")

// this is the Pipeline DSL.
// Syntax here: https://jenkins.io/doc/book/pipeline/syntax/
// More useful docs: https://jenkins.io/doc/pipeline/steps/
pipeline {
  agent none
  options {
    buildDiscarder(logRotator(numToKeepStr: '30', artifactNumToKeepStr: '10000'))
    timeout(time: 180, unit: 'MINUTES')
      }
  environment {
    dockerImageTag    = "${params.dockerBranch}".replace('/','-');
    buildContainers   = true
    }
  stages {
    stage('parallel build base image, infopage, activeMQ and MySQL images') {
      steps {
        script {
          if ( "${buildContainers}" == "true" ) {
            build job: 'build-docker-images',
            parameters: [booleanParam(name: 'buildBase', value: true),
            booleanParam(name: 'buildDatapop', value: false),
            booleanParam(name: 'buildMysql', value: true),
            booleanParam(name: 'buildCortex', value: false),
            booleanParam(name: 'buildSearch', value: false),
            booleanParam(name: 'buildBatch', value: false),
            booleanParam(name: 'buildIntegration', value: false),
            booleanParam(name: 'buildCm', value: false),
            booleanParam(name: 'buildDatasync', value: false),
            booleanParam(name: 'buildActivemq', value: true),
            booleanParam(name: 'infoPage', value: true),
            string(name: 'cloudOpsForKubernetesRepoURL', value: params.cloudOpsForKubernetesRepoURL),
            string(name: 'cloudOpsForKubernetesBranch', value: params.cloudOpsForKubernetesBranch),
            string(name: 'dockerRepoURL', value: params.dockerRepoURL),
            string(name: 'dockerBranch', value: params.dockerBranch),
            string(name: 'dockerCredentialId', value: 'gitCredentialId'),
            string(name: 'tomcatVersion', value: '9.0.16'),
            string(name: 'epCommerceRepoURL', value: params.epCommerceRepoURL),
            string(name: 'epCommerceBranch', value: params.epCommerceBranch),
            string(name: 'deploymentPackageUrl', value: '')
            ]
          } 
        }
      }
    }
  }
}
