apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
        ephemeral-storage: "10Mi"
      limits:
        memory: "512Mi"
        cpu: "200m"
        ephemeral-storage: "10Mi"
  - name: maven
    image: ${dockerRegistryAddress}/jenkins/maven-agent:${jenkinsAgentImageTag}
    imagePullPolicy: "Always"
    command:
    - cat
    tty: true
    resources:
      requests:
        memory: "8704Mi"
        cpu: "2"
        ephemeral-storage: "13Gi"
      limits:
        memory: "8704Mi"
        cpu: "2"
        ephemeral-storage: "13Gi"
    volumeMounts:
    - name: jenkins-secrets-volume
      mountPath: /jenkins-secrets
    - name: root-home-dir-volume
      mountPath: /root/
  dnsConfig:
    options:
      - name: single-request-reopen
      - name: timeout
        value: "3"
      - name: attempts
        value: "3"
  volumes:
  - name: jenkins-secrets-volume
    secret:
      secretName: jenkins-secrets
  - name: root-home-dir-volume
    emptyDir: {}
